In [8]:
from PIL import Image
import PIL
import torch

from torchvision.transforms import transforms

In [9]:
transform_train = transforms.Compose([
            transforms.RandomResizedCrop(224, scale=(0.08, 1.0), interpolation=Image.BICUBIC),
            transforms.RandomHorizontalFlip(),
            transforms.ColorJitter(
                brightness=0.4,
                contrast=0.4,
                saturation=0.4,
            ),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])

In [10]:
transform_train.transforms.insert(0,RandAugment(1,3))

In [23]:
x=torch.randn(10,5)

In [28]:
?x.new()

Object `x.new()` not found.


In [25]:
x.new(10)

tensor([4.0152e+15, 4.5678e-41, 8.3808e-04, 3.0859e-41, 2.3694e-38, 2.3694e-38,
        2.3694e-38, 2.3694e-38, 2.3694e-38, 2.3694e-38])

In [22]:
torch.randn(10,5).new(10)

tensor([8.4073e-04, 3.0859e-41, 8.1938e-04, 3.0859e-41, 6.1972e-04, 7.2443e+22,
        1.7728e+28, 7.0367e+22, 3.7771e-08, 1.0681e-05])

In [13]:
class TSIdentity(Transform):
    "Applies the identity tfm to a `TSTensor` batch"
    order = 90
    def __init__(self, magnitude=0., **kwargs): self.magnitude = magnitude
    def encodes(self, o: TSTensor): return o

NameError: name 'Transform' is not defined

In [14]:
def MagNoise(sig, v):
    return transforms.Lambda(lambda x: x + torch.normal(0, v, (1, x.shape[-1]), dtype=o.dtype, device=o.device))

In [15]:
MagNoise()

TypeError: MagNoise() missing 2 required positional arguments: 'sig' and 'v'

In [16]:
x=torch.randn(2,60)

In [17]:
v=0.2

In [20]:
x

tensor([[-0.1492, -1.8261, -0.0730,  1.2987,  0.2485, -0.4115,  0.7376,  0.1447,
         -0.5095,  1.9805,  0.8510,  0.0825, -0.7728,  0.7053, -1.0807,  0.1666,
         -0.9111, -0.0700, -0.1259,  1.8583,  0.3308,  0.5093, -1.2698, -0.4858,
         -0.1225,  1.4554,  1.2177,  0.0732,  0.3400, -0.8169,  0.7594, -0.9859,
          0.3768,  1.1122, -1.9316,  0.0469,  0.6662, -0.4934,  0.7402, -0.4156,
         -1.4344,  0.7364, -0.7693, -1.8728,  1.6343,  0.6194, -0.4668,  0.0209,
          0.3549, -1.0357, -1.0556, -1.0227, -0.0636,  1.3156, -1.0193, -0.8522,
          0.4838, -2.4667,  2.0858, -0.1311],
        [-0.6787,  1.4303,  2.6095,  0.1984,  0.9222, -2.0364, -0.1814, -2.2953,
          0.5205, -0.5144,  1.8555, -0.4702,  1.2573,  0.3802,  0.8035,  1.2746,
         -0.1554,  0.7639, -2.0861,  0.4353,  1.3842, -0.7780,  1.4653, -1.0936,
          2.2193,  0.2744, -0.8462, -0.4126,  0.5494,  1.0175, -0.0304,  1.8436,
         -1.1497,  1.4294, -0.1185,  1.4685,  2.8088, -1.2390, 

In [19]:
x + torch.normal(0, v, (1, x.shape[-1]), dtype=x.dtype, device=x.device)

tensor([[-0.2700, -1.9427, -0.0630,  1.0774,  0.1945, -0.2150,  1.0289,  0.5202,
         -0.8396,  1.8680,  0.6103,  0.1697, -0.6891,  0.5219, -1.5520,  0.3713,
         -1.3347, -0.1800, -0.2124,  1.4752,  0.0305,  0.5979, -1.3773, -0.5732,
         -0.3990,  1.4565,  1.4217,  0.3920,  0.0047, -0.7800,  0.4653, -1.0437,
          0.3503,  0.8962, -1.9242,  0.1594,  0.5812, -0.3839,  0.6824, -0.0030,
         -1.3261,  0.8258, -0.7698, -2.1344,  1.8929,  0.8600, -0.5603, -0.0820,
          0.5450, -0.9023, -1.2494, -1.2968, -0.2138,  1.0975, -0.9472, -0.8912,
          0.7745, -2.7089,  2.1815, -0.3124],
        [-0.7995,  1.3137,  2.6195, -0.0228,  0.8682, -1.8399,  0.1100, -1.9199,
          0.1904, -0.6270,  1.6148, -0.3830,  1.3410,  0.1968,  0.3323,  1.4792,
         -0.5790,  0.6538, -2.1726,  0.0522,  1.0840, -0.6893,  1.3578, -1.1810,
          1.9427,  0.2755, -0.6422, -0.0938,  0.2141,  1.0544, -0.3245,  1.7858,
         -1.1761,  1.2134, -0.1110,  1.5810,  2.7238, -1.1295, 

In [30]:
import numpy as np
np.random.beta

<function RandomState.beta>

In [33]:
np.random.beta(0.1,0.1)

6.670390640269815e-10

In [48]:
ls = [[[[1,2,3,4,5],[6,7,8,9,10]]]]

In [53]:
torch.tensor(ls)[:,0,...].shape

torch.Size([1, 2, 5])

In [50]:
torch.tensor(ls).shape

torch.Size([1, 1, 2, 5])

In [55]:
from torchvision.transforms import transforms
from RandAugment import RandAugment

transform_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(_CIFAR_MEAN, _CIFAR_STD),
])

# Add RandAugment with N, M(hyperparameter)
transform_train.transforms.insert(0, RandAugment(N, M))

IndentationError: unindent does not match any outer indentation level (augmentations.py, line 87)